name: Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false

      - name: Set up uv
        uses: astral-sh/setup-uv@f59926e2e5b41075beaa4cb803a67035cf086c0e # v5.2.1
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Build documentation
        run: uv run zensical build --strict

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dee4b66cfe43 # v3.0.1
        with:
          path: ./site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db596a5aa6d426a84e5a6640237e54be55f0ee # v4.0.5
